import Foundation
import Testing
@testable import ClipboardCore

@Suite struct PasteboardClassifierTests {
    private struct Case: CustomTestStringConvertible, Sendable {
        var name: String
        var snapshot: PasteboardSnapshot
        var expected: PasteboardClassifier.Outcome
        var testDescription: String { name }
    }

    private static let png = Data([0x89, 0x50, 0x4E, 0x47])
    private static let policy: ClipboardPolicy = {
        var policy = ClipboardPolicy()
        policy.maxImageBytes = 4
        policy.maxTextBytes = 5
        return policy
    }()

    private static let cases: [Case] = [
        Case(name: "concealed type",
             snapshot: .init(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"], string: "hunter2"),
             expected: .skip(.concealed)),
        Case(name: "transient type",
             snapshot: .init(types: ["org.nspasteboard.TransientType"], string: "otp"),
             expected: .skip(.concealed)),
        Case(name: "auto-generated type",
             snapshot: .init(types: ["org.nspasteboard.AutoGeneratedType"], string: "gen"),
             expected: .skip(.concealed)),
        Case(name: "own marker",
             snapshot: .init(types: ["dev.warden.clipboard.own"], string: "ours"),
             expected: .skip(.ownWrite)),
        Case(name: "concealed wins over files",
             snapshot: .init(types: ["org.nspasteboard.ConcealedType"], filePaths: ["/tmp/a"]),
             expected: .skip(.concealed)),
        Case(name: "Finder copy: file URL + name string + icon image is files",
             snapshot: .init(types: ["public.file-url", "public.utf8-plain-text", "public.png"],
                             filePaths: ["/tmp/a.txt"], string: "a.txt", imageData: png),
             expected: .capture(.files(["/tmp/a.txt"]))),
        Case(name: "text + RTF + image is text",
             snapshot: .init(types: ["public.utf8-plain-text", "public.rtf", "public.png"], string: "cell", imageData: png),
             expected: .capture(.text("cell"))),
        Case(name: "image + URL string without RTF is image",
             snapshot: .init(types: ["public.utf8-plain-text", "public.png"], string: "https://x.test/a.png", imageData: png),
             expected: .capture(.image(png))),
        Case(name: "image alone",
             snapshot: .init(types: ["public.png"], imageData: png),
             expected: .capture(.image(png))),
        Case(name: "image above the limit is too large, not text",
             snapshot: .init(types: ["public.utf8-plain-text", "public.png"], string: "x", imageData: png + [0]),
             expected: .skip(.tooLarge)),
        Case(name: "text at the limit",
             snapshot: .init(types: ["public.utf8-plain-text"], string: "12345"),
             expected: .capture(.text("12345"))),
        Case(name: "text above the limit counts UTF-8 bytes",
             snapshot: .init(types: ["public.utf8-plain-text"], string: "ééé"),
             expected: .skip(.tooLarge)),
        Case(name: "whitespace-only text",
             snapshot: .init(types: ["public.utf8-plain-text"], string: " \n\t "),
             expected: .skip(.empty)),
        Case(name: "empty string",
             snapshot: .init(types: ["public.utf8-plain-text"], string: ""),
             expected: .skip(.empty)),
        Case(name: "nothing usable",
             snapshot: .init(types: ["com.example.private"]),
             expected: .skip(.empty)),
    ]

    @Test(arguments: cases)
    private func classifies(_ c: Case) {
        #expect(PasteboardClassifier.classify(c.snapshot, policy: Self.policy) == c.expected)
    }
}
