import Foundation
import MonitorModel

/// Which project build dirs are safe to offer (spec §6.3 "project build dirs"). The scanner flags the names and
/// records the tool markers; this holds the rule, the classifier applies it over the tree.
enum BuildDirRules {
    /// Project untouched for this long (`subtreeMaxMtime` excludes build dirs, so a fresh install doesn't count).
    static let projectAge: TimeInterval = 30 * 86400

    /// Marker files (any one) that prove a dir was generated by its tool; nil if `name` is not a build dir name.
    static func requiredMarkers(forName name: String) -> StorageMarker? {
        switch name {
        case "node_modules": [.npmLock, .pnpmModules, .yarnState]
        case ".build": [.swiftpmWorkspaceState]
        case "target": [.cachedirTag]
        case "Pods": [.podsManifest]
        case "build": [.cmakeCache, .cachedirTag]
        case _ where name.hasPrefix("cmake-build-"): [.cmakeCache]
        default: nil
        }
    }

    /// The `.git` ancestor a build dir belongs to, searching up to (and including) `limit`.
    static func project(of node: StorageNodeID, in tree: StorageTree, limit: StorageNodeID) -> StorageNodeID? {
        var n = tree.parent[Int(node)]
        while n >= limit {
            if tree.markerMask[Int(n)].contains(.git) { return n }
            if n == 0 { break }
            n = tree.parent[Int(n)]
        }
        return nil
    }
}
