import Foundation

/// What the watcher read from the general pasteboard; the classifier needs nothing else.
public struct PasteboardSnapshot: Equatable, Sendable {
    public var types: Set<String>
    public var filePaths: [String]
    public var string: String?
    /// `public.png`, else `public.tiff`.
    public var imageData: Data?

    public init(types: Set<String> = [], filePaths: [String] = [], string: String? = nil, imageData: Data? = nil) {
        self.types = types
        self.filePaths = filePaths
        self.string = string
        self.imageData = imageData
    }
}

public enum PasteboardClassifier {
    public static let ownMarkerType = "dev.warden.clipboard.own"
    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ]
    static let rtfType = "public.rtf"

    public enum Skip: Equatable, Sendable { case concealed, ownWrite, empty, tooLarge }
    public enum Outcome: Equatable, Sendable { case capture(ClipCapture.Content), skip(Skip) }

    public static func classify(_ snapshot: PasteboardSnapshot, policy: ClipboardPolicy = .default) -> Outcome {
        if !snapshot.types.isDisjoint(with: concealedTypes) { return .skip(.concealed) }
        if snapshot.types.contains(ownMarkerType) { return .skip(.ownWrite) }

        if !snapshot.filePaths.isEmpty { return .capture(.files(snapshot.filePaths)) }

        // Office apps put a picture of the selection next to text + RTF; that is a text copy.
        let isRichText = snapshot.string != nil && snapshot.types.contains(rtfType)
        if let image = snapshot.imageData, !image.isEmpty, !isRichText {
            return image.count > policy.maxImageBytes ? .skip(.tooLarge) : .capture(.image(image))
        }

        if let text = snapshot.string {
            if text.allSatisfy(\.isWhitespace) { return .skip(.empty) }
            return text.utf8.count > policy.maxTextBytes ? .skip(.tooLarge) : .capture(.text(text))
        }
        return .skip(.empty)
    }
}
